version: "3.3"
services: 
  app:
    build: web
    image: flowerssql-app
    ports:
      - 3000:3000
  db: 
    build: db
    image: flowerssql-db
    volumes: 
      - flowers-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
volumes:
  flowers-data:

